name: 🗼 Lighthouse Report

on:
  workflow_call:
    inputs:
      url:
        required: true
        type: string
      environment-name:
        required: false
        type: string
        default: "lighthouse-report"
    secrets:
      REPO_TOKEN:
        required: true

jobs:
  lighthouse:
    environment:
      name: ${{ inputs.environment-name}}
      url: ${{ steps.report.outputs.url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Audit URLs using Lighthouse
        id: lhci
        uses: treosh/lighthouse-ci-action@v10
        with:
          urls: ${{ inputs.url }}
          uploadArtifacts: false
          temporaryPublicStorage: true
      - name: Get Lighthouse Report URL
        id: report
        run: echo url=$(echo '${{ steps.lhci.outputs.links }}' | jq -r 'first(.[])') >> $GITHUB_OUTPUT
