name: 🗼 Lighthouse Report

on:
  workflow_call:
    inputs:
      url:
        required: true
        type: string
      environment-name:
        required: false
        type: string
        default: "lighthouse-report"
    secrets:
      REPO_TOKEN:
        required: true

jobs:
  lighthouse:
    environment:
      name: ${{ inputs.environment-name}}
      url: ${{ steps.report.outputs.url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: Audit URLs using Lighthouse
        id: lhci
        uses: treosh/lighthouse-ci-action@3e7e23fb74242897f95c0ba9cabad3d0227b9b18 # v12.6.2
        with:
          urls: ${{ inputs.url }}
          uploadArtifacts: false
          temporaryPublicStorage: true

      - name: Get Lighthouse Report URL
        id: report
        run: echo url=$(echo '${{ steps.lhci.outputs.links }}' | jq -r 'first(.[])') >> $GITHUB_OUTPUT
