name: 🚀 Deploy to GitHub Pages

on:
  workflow_call:
    outputs:
      url:
        description: "GitHub Pages deployment URL"
        value: ${{ jobs.deploy.outputs.url }}
    inputs:
      artifact-name:
        required: true
        type: string
      file-name:
        required: false
        type: string
        default: ""
      environment-name:
        required: false
        type: string
        default: "github-pages"
    secrets:
      REPO_TOKEN:
        required: true

jobs:
  deploy:
    environment:
      name: ${{ inputs.environment-name }}
      url: ${{ steps.deployment.outputs.page_url }}${{ inputs.file-name }}
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    outputs:
      url: ${{ steps.deployment.outputs.page_url }}${{ inputs.file-name }}
    steps:
      - name: 📦 Download build artifact
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: ${{ inputs.artifact-name }}

      - name: 🏗️ Setup GitHub Pages
        uses: actions/configure-pages@45bfe0192ca1faeb007ade9deae92b16b8254a0d # v6.0.0
        with:
          token: ${{ secrets.REPO_TOKEN }}

      - name: 📦 Create and upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5.0.0
        with:
          path: ./
          name: "pages-${{ inputs.artifact-name }}"
          retention-days: 1

      - name: 🚀 Deploy GitHub Pages artifact
        id: deployment
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5.0.0
        with:
          token: ${{ secrets.REPO_TOKEN }}
          artifact_name: "pages-${{ inputs.artifact-name }}"
