name: simple test

on:
  workflow_dispatch:

  workflow_call:
    inputs:
      gh-ref:
        type: string
        required: false
        default: ${{ github.ref }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: |
          echo 'is this thing on?'
          echo 'ref: ${{ inputs.gh-ref }}'

